-- Admin security hardening — run this once, manually, in the Supabase SQL
-- Editor, in this order. Neither table grants anything to anon or
-- authenticated: only the server-side admin actions (using the
-- service_role key) ever need to touch these, so those two roles get no
-- access at all, on top of RLS being enabled with no policies for them.

-- ── Part A: admin_login_attempts ───────────────────────────────────────
-- one row per login attempt (successful or not), used to count failures
-- in the last 15 minutes and lock out further attempts once there are 5+.
create table if not exists public.admin_login_attempts (
  id           bigint generated by default as identity primary key,
  attempted_at timestamptz not null default now(),
  success      boolean not null
);

create index if not exists admin_login_attempts_attempted_at_idx
  on public.admin_login_attempts (attempted_at);

alter table public.admin_login_attempts enable row level security;

grant select, insert on public.admin_login_attempts to service_role;


-- ── Part B: admin_sessions ──────────────────────────────────────────────
-- one row per active login — the cookie stores "token"; isAdminAuthed()
-- checks a matching, non-expired row exists here instead of recomputing a
-- fixed value.
create table if not exists public.admin_sessions (
  id         bigint generated by default as identity primary key,
  token      text not null unique,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null
);

alter table public.admin_sessions enable row level security;

grant select, insert, delete on public.admin_sessions to service_role;
